#
# This Kustomization puts all under
# resources specified files together.
#
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./ingress.yaml
- ./deployment.yaml
- ./service.yaml

images:
- name: frontend
  newName: vikunja/frontend
  newTag: "0.19.0"

commonLabels:
  app.kubernetes.io/component: app

vars:
- name: VIKUNJA_FRONTEND_URL
  objref:
    name: vikunja-frontend
    group: networking.k8s.io
    apiVersion: v1
    kind: Ingress
  fieldref:
    fieldpath: spec.rules.0.host

## references for using variables
configurations:
- varreferences.yaml