apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/service: database
type: Opaque
stringData:
  username: root
  password: <supersecretpassword>
  database: vikunja