apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-backend
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vikunja-backend
      app.kubernetes.io/service: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vikunja-backend
        app.kubernetes.io/service: backend
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: api
        image: backend
        imagePullPolicy: Always

        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: VIKUNJA_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres
        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres
        - name: VIKUNJA_DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: postgres
        - name: VIKUNJA_DATABASE_HOST
          value: "postgres"
        - name: VIKUNJA_DATABASE_TYPE
          value: "postgres"
        - name: VIKUNJA_SERVICE_FRONTENDURL
          value: "$(VIKUNJA_FRONTEND_URL)"
        envFrom:
          - secretRef:
              name: database
          - secretRef:
              name: vikunja-backend-mail-secret
          - configMapRef:
              name: config
        ports:
          - name: http
            containerPort: 3456
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 3456
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128M"
            cpu: "100m"
          limits:
            memory: "1024M"
            cpu: "500m"
        volumeMounts:
        - name: vikunja-backend
          mountPath: /app/vikunja/files
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
        - name: vikunja-backend
          persistentVolumeClaim:
            claimName: vikunja-backend