#
# This Kustomization puts all under
# resources specified files together.
#
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./ingress.yaml
- ./deployment.yaml
- ./pvc.yaml
- ./service.yaml
- ./secret/vikunja-secret.yaml

images:
- name: backend
  newName: vikunja/api
  newTag: "0.19.0"

commonLabels:
  app.kubernetes.io/component: app

configMapGenerator:
 - name: config
   envs:
    - config/envs.txt

vars:
- name: VIKUNJA_BACKEND_URL
  objref:
    name: vikunja-backend
    group: networking.k8s.io
    apiVersion: v1
    kind: Ingress
  fieldref:
    fieldpath: spec.rules.0.host

## references for using variables
configurations:
- varreferences.yaml