apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: vikunja-backend
    app.kubernetes.io/service: backend
  name: vikunja-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
