apiVersion: v1
stringData:
  VIKUNJA_MAILER_FROMEMAIL: vikunja@example.com
  VIKUNJA_MAILER_HOST: smtp.example.com
  VIKUNJA_MAILER_PORT: "25"
  VIKUNJA_MAILER_USERNAME: vikunja@example.com
  VIKUNJA_MAILER_PASSWORD: <supersecretpassword>
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: vikunja-backend
    app.kubernetes.io/service: backend
  name: vikunja-backend-mail-secret
type: Opaque